# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: "[[ $(git branch --show-current) == develop ]] && echo 'hi'"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and develop your project.
      
      - name: rewrite version
        run: ./increment_version_number.py
       
        
      - name: echo version.txt
        run: cat version.txt
        
      - name: echo branch
        run: git branch --show-current
       
      - name: check branch
        run: git status

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
    # Optional but recommended
    # Defaults to "Apply automatic changes"
    #commit_message: Apply automatic changes

    # Optional branch name where commit should be pushed to
    # Defaults to the current branch
          branch: develop

    # Optional options appended  to `git-commit`
    # See https://git-scm.com/docs/git-commit for a list of available options
          commit_options: '--no-verify --signoff --amend --no-edit'

    # Optional glob pattern of files which should be added to the commit
    # Defaults to all (.)
    # See the `pathspec`-documentation for git
    # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
    # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: version.txt

    # Optional local file path to the repository
    # Defaults to the root of the repository
          repository: .

    # Optional commit user and author settings
    #commit_user_name: ${GITHUB_ACTOR} # defaults to "GitHub Actions"
    #commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
    #commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run



    # Optional options appended to `git-push`
    # See git-push documentation for details: https://git-scm.com/docs/git-push#_options
          push_options: '--force'
    
    # Optional: Disable dirty check and always try to create a commit and push
          skip_dirty_check: true    
    
    # Optional: Skip internal call to `git fetch`
          skip_fetch: true        

      #    git pull
      #    git add version.txt
      #    git commit --amend --no-edit
      #    git push -f
          
