# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: "[[ $(git branch --show-current) == develop ]] && echo 'hi'"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          build_name="this si buidls"
          echo "Add other actions to build, ${build_name}"
          echo $build_name
      
      - name: rewrite version
        run: ./increment_version_number.py
       
        
      - name: echo version.txt
        run: pwd
        
      - name: echo branch
        run: git branch --show-current
       
      - name: now amend
        run: |
          ./increment_version_number.py
          git config --global user.name MATTHEWFRAZER
          git config --global user.email mfrazeriguess@gmail.com
          git add version.txt
          git commit --amend --no-edit
          git push -f
